name: Trigger Depoly
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - docusaurus
jobs:
  call_orkflow:
    uses: SurFlurer/CDDA-CN-Guide/.github/workflows/documentation.yml@docusaurus
